// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcoOkAcAuvLZ9AlJzMn2BoGmgqihUk1-8',
    appId: '1:392326867102:android:1e2dc722b9fb995f42f38f',
    messagingSenderId: '392326867102',
    projectId: 'rni-home-services',
    storageBucket: 'rni-home-services.firebasestorage.app',
  );

  // These values, not ios/Runner/GoogleService-Info.plist, are what actually
  // configure Firebase here: main.dart calls initializeApp with
  // DefaultFirebaseOptions.currentPlatform. The plist sits alongside them for
  // the Firebase iOS SDK's own use and must still be added to the Runner
  // target in Xcode -- it is on disk but not yet referenced by the project,
  // which cannot be done from Windows. See ios/README-firebase.md.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyisgCYmXFDGVGkRFk-FphwJyMuIBTvLY',
    appId: '1:392326867102:ios:367aaf5d3e5ef27b42f38f',
    messagingSenderId: '392326867102',
    projectId: 'rni-home-services',
    storageBucket: 'rni-home-services.firebasestorage.app',
    iosBundleId: 'com.rniservices.vendor',
  );
}
