// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcoOkAcAuvLZ9AlJzMn2BoGmgqihUk1-8',
    appId: '1:392326867102:android:1e2dc722b9fb995f42f38f',
    messagingSenderId: '392326867102',
    projectId: 'rni-home-services',
    storageBucket: 'rni-home-services.firebasestorage.app',
  );

  // STILL THE OLD PROJECT. Android has moved to the client's Firebase project
  // (rni-home-services); iOS has not, because its GoogleService-Info.plist has
  // not been issued yet. Replace all six values from that file when it arrives.
  //
  // Nothing is broken by this today -- an iOS build needs a Mac, which is not
  // set up yet, so this path is unreachable. It is only dangerous the moment
  // someone does build for iPhone: push would silently register against a
  // Firebase project the client does not own, and no notification the backend
  // sends would ever arrive.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjplCQd9VkhksKszwsA3dsQQtt9MoK-64',
    appId: '1:879153194201:ios:768f8fb58ef5c1bebbcac8',
    messagingSenderId: '879153194201',
    projectId: 'prohome-8f3c8',
    storageBucket: 'prohome-8f3c8.firebasestorage.app',
    iosBundleId: 'com.rniservices.vendor',
  );
}
